version: "3.8"

services:

  #DATABASE
  database:
    container_name: database_tube_miner
    image: postgres:14.1
    networks:
      - tube_miner_net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_NAME=${POSTGRES_NAME}
    volumes:
      - database_tube_miner:/var/lib/postgresql
      - database_tube_miner_data:/var/lib/postgresql/data
  
  redis:
    image: redis
    hostname: redis
    networks:
      - tube_miner_net
    command: redis-server --save "" --appendonly no --maxclients 20000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'


networks:
  tube_miner_net:

volumes:
  database_tube_miner:
  database_tube_miner_data:
  rabbitmq_tube_miner_vol: