version: "3.8"

services:

  #DATABASE
  database:
    container_name: database_tube_miner
    image: postgres:14.1
    networks:
      - tube_miner_net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_tube_miner:/var/lib/postgresql
      - database_tube_miner_data:/var/lib/postgresql/data


networks:
  tube_miner_net:

volumes:
  database_tube_miner:
  database_tube_miner_data:
  rabbitmq_tube_miner_vol:

